---
- name: Enable cgroup via boot commandline if not already enabled
  ansible.builtin.replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ cgroup_item }}\b).*)$'
    replace: '\1 {{ cgroup_item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  loop_control:
    loop_var: cgroup_item
  notify: reboot

- meta: flush_handlers

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

# IPtables versions 1.6.1 and older have problems with K3s, so we force the use of
# iptables-legacy in that case.
- name: If old iptables found, change to iptables-legacy
  when:
    - ansible_facts.packages['iptables'] is defined
    - ansible_facts.packages['iptables'][0]['version'] is version('1.6.2', '<')
  block:
    - name: Iptables version on node
      ansible.builtin.debug:
        msg: "iptables version {{ ansible_facts.packages['iptables'][0]['version'] }} found"

    - name: Flush iptables before changing to iptables-legacy
      ansible.builtin.iptables:
        flush: true
      changed_when: false   # iptables flush always returns changed

    - name: Changing to iptables-legacy
      community.general.alternatives:
        path: /usr/sbin/iptables-legacy
        name: iptables
      register: ip4_legacy

    - name: Changing to ip6tables-legacy
      community.general.alternatives:
        path: /usr/sbin/ip6tables-legacy
        name: ip6tables
      register: ip6_legacy

- name: Get k3s installed version
  ansible.builtin.command: k3s --version
  register: k3s_version_output
  changed_when: false
  ignore_errors: true

- name: Set k3s installed version
  when: k3s_version_output.rc == 0
  ansible.builtin.set_fact:
    installed_k3s_version: "{{ k3s_version_output.stdout_lines[0].split(' ')[2] }}"

# If airgapped, all K3s artifacts are already on the node.
# We should be downloading and installing the newer version only if we are in one of the following cases :
#   - we couldn't get k3s installed version in the first task of this role
#   - the installed version of K3s on the nodes is older than the requested version in ansible vars
- name: Download artifact only if needed
  when: k3s_version_output.rc != 0 or installed_k3s_version is version(k3s_version, '<') and airgap_dir is undefined
  block:
    - name: Download K3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io/
        timeout: 120
        dest: /usr/local/bin/k3s-install.sh
        owner: root
        group: root
        mode: "0755"

    - name: Download K3s binary
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-install.sh
      environment:
        INSTALL_K3S_SKIP_START: "true"
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
      changed_when: true

- name: Add K3s autocomplete to user bashrc
  ansible.builtin.lineinfile:
    path: "~{{ ansible_user }}/.bashrc"
    regexp: '\.\s+<\(k3s completion bash\)'
    line: ". <(k3s completion bash)  # Added by k3s-ansible"

- name: Setup optional config file
  when: server_config_yaml is defined
  block:
    - name: Make config directory
      ansible.builtin.file:
        path: "/etc/rancher/k3s"
        mode: "0755"
        state: directory
    - name: Copy config values
      ansible.builtin.copy:
        content: "{{ server_config_yaml }}"
        dest: "/etc/rancher/k3s/config.yaml"
        mode: "0644"

- name: Init first server node
  when: inventory_hostname == groups[k3s_server_group][0]
  block:
    - name: Copy K3s service file [Single]
      when: groups[k3s_server_group] | length == 1 or raspberrypi4_k3s_server_use_external_database
      ansible.builtin.template:
        src: "k3s-single.service.j2"
        dest: "/etc/systemd/system/k3s.service"
        owner: root
        group: root
        mode: "0644"
      register: service_file_single

    - name: Copy K3s service file [HA]
      when:
        - groups[k3s_server_group] | length > 1
        - not raspberrypi4_k3s_server_use_external_database
      ansible.builtin.template:
        src: "k3s-cluster-init.service.j2"
        dest: "/etc/systemd/system/k3s.service"
        owner: root
        group: root
        mode: "0644"
      register: service_file_ha

    - name: Add service environment variables
      when: extra_service_envs is defined
      ansible.builtin.lineinfile:
        path: "/etc/systemd/system/k3s.service.env"
        line: "{{ item }}"
      with_items: "{{ extra_service_envs }}"

    - name: Restart K3s service
      when:
        - ansible_facts.services['k3s.service'] is defined
        - ansible_facts.services['k3s.service'].state == 'running'
        - service_file_single.changed or service_file_ha.changed
      ansible.builtin.systemd:
        name: k3s
        daemon_reload: true
        state: restarted

    - name: Enable and check K3s service
      when: ansible_facts.services['k3s.service'] is not defined or ansible_facts.services['k3s.service'].state != 'running'
      ansible.builtin.systemd:
        name: k3s
        daemon_reload: true
        state: started
        enabled: true

    - name: Pause to allow first server startup
      when: (groups[k3s_server_group] | length) > 1
      ansible.builtin.pause:
        seconds: 10

    - name: Check whether kubectl is installed on control node
      ansible.builtin.command: 'kubectl'
      register: kubectl_installed
      ignore_errors: true
      delegate_to: 127.0.0.1
      become: false
      changed_when: false

    # Copy the k3s config to a second file to detect changes.
    # If no changes are found, we can skip copying the kubeconfig to the control node.
    - name: Copy k3s.yaml to second file
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /etc/rancher/k3s/k3s-copy.yaml
        mode: "0600"
        remote_src: true
      register: copy_k3s_yaml_file

    - name: Apply K3S kubeconfig to control node
      when:
        - kubectl_installed.rc == 0
        - copy_k3s_yaml_file.changed
      block:
        - name: Copy kubeconfig to control node
          ansible.builtin.fetch:
            src: /etc/rancher/k3s/k3s.yaml
            dest: "{{ raspberrypi4_k3s_server_kubeconfig }}"
            flat: true

        - name: Change server address in kubeconfig on control node
          ansible.builtin.shell: |
            KUBECONFIG={{ raspberrypi4_k3s_server_kubeconfig }} kubectl config set-cluster default --server=https://{{ k3s_api_endpoint }}:{{ k3s_api_port }}
          delegate_to: 127.0.0.1
          become: false
          register: csa_result
          changed_when:
            - csa_result.rc == 0

        - name: Setup kubeconfig context on control node - {{ raspberrypi4_k3s_server_cluster_context }}
          when: raspberrypi4_k3s_server_kubeconfig != "~/.kube/config"
          ansible.builtin.replace:
            path: "{{ raspberrypi4_k3s_server_kubeconfig }}"
            regexp: 'name: default'
            replace: 'name: {{ raspberrypi4_k3s_server_cluster_context }}'
          delegate_to: 127.0.0.1
          become: false

        - name: Merge with any existing kubeconfig on control node
          when: raspberrypi4_k3s_server_kubeconfig != "~/.kube/config"
          ansible.builtin.shell: |
            TFILE=$(mktemp)
            KUBECONFIG={{ raspberrypi4_k3s_server_kubeconfig }} kubectl config set-context {{ raspberrypi4_k3s_server_cluster_context }} --user={{ raspberrypi4_k3s_server_cluster_context }} --cluster={{ raspberrypi4_k3s_server_cluster_context }}
            KUBECONFIG={{ raspberrypi4_k3s_server_kubeconfig }} kubectl config view --flatten > ${TFILE}
            mv ${TFILE} {{ raspberrypi4_k3s_server_kubeconfig }}
          delegate_to: 127.0.0.1
          become: false
          register: mv_result
          changed_when:
            - mv_result.rc == 0

- name: Start other server if any and verify status
  when:
    - (groups[k3s_server_group] | length) > 1
    - inventory_hostname != groups[k3s_server_group][0]
  block:
    - name: Copy K3s service file [HA]
      when: not raspberrypi4_k3s_server_use_external_database
      ansible.builtin.template:
        src: "k3s-ha.service.j2"
        dest: "/etc/systemd/system/k3s.service"
        owner: root
        group: root
        mode: "0644"
      register: service_file_ha

    - name: Copy K3s service file [External DB]
      when: raspberrypi4_k3s_server_use_external_database
      ansible.builtin.template:
        src: "k3s-single.service.j2"
        dest: "/etc/systemd/system/k3s.service"
        owner: root
        group: root
        mode: "0644"
      register: service_file_external_db

    - name: Restart K3s service
      when:
        - ansible_facts.services['k3s.service'] is defined
        - ansible_facts.services['k3s.service'].state == 'running'
        - service_file_ha.changed or service_file_external_db.changed
      ansible.builtin.systemd:
        name: k3s
        daemon_reload: true
        state: restarted

    - name: Enable and check K3s service
      when: ansible_facts.services['k3s.service'] is not defined or ansible_facts.services['k3s.service'].state != 'running'
      ansible.builtin.systemd:
        name: k3s
        daemon_reload: true
        state: started
        enabled: true

    - name: Verify that all server nodes joined
      when: (groups[k3s_server_group] | length) > 1
      ansible.builtin.command:
        cmd: >
          k3s kubectl get nodes -l "node-role.kubernetes.io/control-plane=true" -o=jsonpath="{.items[*].metadata.name}"
      register: nodes
      until: nodes.rc == 0 and (nodes.stdout.split() | length) == (groups[k3s_server_group] | length)
      retries: 20
      delay: 10
      changed_when: false

- name: Setup kubectl for user
  when: raspberrypi4_k3s_server_user_kubectl
  block:
    - name: Create kubectl symlink
      when: lookup('fileglob', '/usr/local/bin/kubectl', errors='warn') | length == 0
      ansible.builtin.file:
        src: /usr/local/bin/k3s
        dest: /usr/local/bin/kubectl
        state: link

    - name: Create directory .kube
      ansible.builtin.file:
        path: ~{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        mode: "u=rwx,g=rx,o="

    - name: Copy config file to user home directory
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~{{ ansible_user }}/.kube/config
        remote_src: true
        owner: "{{ ansible_user }}"
        mode: "u=rw,g=,o="

    - name: Configure default KUBECONFIG for user
      ansible.builtin.lineinfile:
        path: ~{{ ansible_user }}/.bashrc
        regexp: 'export KUBECONFIG=~/.kube/config'
        line: 'export KUBECONFIG=~/.kube/config # Added by k3s-ansible'
        state: present

    - name: Configure kubectl autocomplete
      ansible.builtin.lineinfile:
        path: ~{{ ansible_user }}/.bashrc
        regexp: '\.\s+<\(kubectl completion bash\)'
        line: ". <(kubectl completion bash)  # Added by k3s-ansible"

- name: Mount k3s persistent files in /data
  ansible.builtin.include_role:
    name: mount_in_data
  vars:
    path: "{{ item.path }}"
  with_items:
    - path: /var/lib/rancher/k3s/agent/containerd/
  when: "{{ raspberrypi_readonly|default(false) }}"

- name: Mount k3s runtime files in tmpfs
  ansible.builtin.include_role:
    name: mount_in_tmpfs
  vars:
    path: "{{ item.path }}"
    backup: "{{ item.backup|default(true) }}"
    systemd_service_id: "{{ item.id }}"
    systemd_restore_before: k3s.service
  with_items:
    - path: /etc/rancher/k3s/
      id: k3s_config
    - path: /var/lib/rancher/k3s/server/
      id: k3s_server
    - path: /var/lib/kubelet/
      id: k3s_kubelet
      backup: false
    - path: /var/lib/cni/
      id: k3s_cni
      backup: false
    - path: /var/lib/rancher/k3s/agent/etc/
      id: k3s_agent_etc
    - path: /var/lib/rancher/k3s/agent/client-ca.crt
      id: k3s_agent_client_ca
    - path: /var/lib/rancher/k3s/agent/server-ca.crt
      id: k3s_agent_server_ca
    - path: /var/lib/rancher/k3s/agent/serving-kubelet.crt
      id: k3s_agent_serving_kubelet_cert
    - path: /var/lib/rancher/k3s/agent/serving-kubelet.key
      id: k3s_agent_serving_kubelet_key
    - path: /var/lib/rancher/k3s/agent/client-kubelet.crt
      id: k3s_agent_client_kubelet_cert
    - path: /var/lib/rancher/k3s/agent/client-kubelet.key
      id: k3s_agent_client_kubelet_key
    - path: /var/lib/rancher/k3s/agent/client-kube-proxy.crt
      id: k3s_agent_client_kube_proxy_cert
    - path: /var/lib/rancher/k3s/agent/client-kube-proxy.key
      id: k3s_agent_client_kube_proxy_key
    - path: /var/lib/rancher/k3s/agent/client-k3s-controller.crt
      id: k3s_agent_client_k3s_controller_cert
    - path: /var/lib/rancher/k3s/agent/client-k3s-controller.key
      id: k3s_agent_client_k3s_controller_key
    - path: /var/lib/rancher/k3s/agent/k3scontroller.kubeconfig
      id: k3s_agent_k3s_controller_config
    - path: /var/lib/rancher/k3s/agent/kubelet.kubeconfig
      id: k3s_agent_kubelet_config
    - path: /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig
      id: k3s_agent_kube_proxy_config
  when: "{{ raspberrypi_readonly|default(false) }}"

- name: Restart k3s
  ansible.builtin.systemd_service:
    name: "k3s"
    state: "restarted"
  changed_when: false

- name: Download kubeconfig
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /tmp
  changed_when: false
  register: download

- name: Replice IP in kubeconfig
  ansible.builtin.replace:
    path: "{{ download.dest }}"
    regexp: '(127\.0\.0\.1)'
    replace: "{{ ansible_host }}"
  delegate_to: 127.0.0.1
  changed_when: false

- name: Create ~/.kube
  ansible.builtin.file:
    path: "~/.kube"
    state: directory
  delegate_to: 127.0.0.1

- name: Copy kubeconfig in ~/.kube/config
  ansible.builtin.copy:
    src: "{{ download.dest }}"
    dest: ~/.kube/config
  delegate_to: 127.0.0.1
